inherit_from: .rubocop_todo.yml

# rubocop関連のgemをrequireする。
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'app/models/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Rails:
  Enabled: true

# 日本語のコメントを許可する。
Style/AsciiComments:
  Enabled: false

Style/PerlBackrefs:
  AutoCorrect: false
